### ISSUE TITLE
Allow key properties to be used as inputs to Heat templates

### ISSUE THREAD

**Issue by dvaccarosenna** [accanto-systems/openstack-vim-driver#39]
Currently any property marked as "key" in a Resource descriptor will have it's value replaced by Brent with "keyName", "privateKey" and "publicKey" values. 

In a Heat template, we cannot reference any of these as an input property. If we reference the name of the key as an input we get a concatenation of private and public key instead.

E.g. in the following case, on a create infrastructure request, "my_key" will be populated with the concatenated value. 
```
parameters:
  my_key:
    type: string
```

It would be better if we could reference the 3 separate parts of the key:
```
parameters:
  # This will be populated with the "keyName"
  my_key:
    type: string
  # This will be populated with the "privateKey"
  my_key_private:
    type: string
  # This will be populated with the "publicKey"
  my_key_public:
    type: string
```
