### ISSUE TITLE
Include resource requests and limits configuration in Helm chart

### ISSUE THREAD

**Issue by dvaccarosenna** [accanto-systems/openstack-vim-driver#5]
It is common when creating a Pod to define the resources it will use (CPU and Memory) on a Kubernetes node. 

It is also common for most helm charts to allow these parameters to be configurable. 

We should consider adding Pod resource limits and requests values to our Helm Charts, making them configurable though the helm chart values. 

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

The majority of helm charts available on the public repository allow the resources to be configured through the following values:

```
resources:    
  limits:      
    cpu: "1"      
    memory: "2048Mi"
  requests:
    cpu: "25m"      
    memory: "1536Mi"
```
